### ISSUE TITLE
Zotero > 'Add reference' doesn't work

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/neurocurator#17]
Steps:
1. Click on _Zotero_ in the menu bar then on _Add reference_.
2. Nothing happens (on the application side).

Stack trace:
```
Traceback (most recent call last):
  File "/Users/fonta/repos/neurocurator/neurocurator/mainWin.py", line 378, in addToZotLib
    addToZoteroDlg = AddToZoteroDlg(self.zoteroTableModel, self)
  File "/Users/fonta/repos/neurocurator/neurocurator/addToZoteroDlg.py", line 62, in __init__
    self.loadReference(row)            
  File "/Users/fonta/repos/neurocurator/neurocurator/addToZoteroDlg.py", line 69, in loadReference
    item = self.zotWrapTable.zotWrap.refList[row]
TypeError: list indices must be integers, not Window
```

**Comment by pafonta** [comment]
Fixed in [v0.4.0](https://github.com/BlueBrain/neurocurator/tree/v0.4.0).
