### ISSUE TITLE
Paper Zotero database: sorting by 'Annotations' doesn't work

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/neurocurator#18]
Steps:

1. Click on the column header _Annotations_ in the _Paper Zotero database_ tab.
2. Nothing happens (the rows are not sorted).

Stack trace:

```
Traceback (most recent call last):
  File "/Users/fonta/repos/neurocurator/neurocurator/zoteroWrap.py", line 168, in sort
    self.zotWrap.refList = sorted(self.zotWrap.refList, key=lambda x: self.getByIndex(x, col).lower(), reverse = reverse)
  File "/Users/fonta/repos/neurocurator/neurocurator/zoteroWrap.py", line 168, in <lambda>
    self.zotWrap.refList = sorted(self.zotWrap.refList, key=lambda x: self.getByIndex(x, col).lower(), reverse = reverse)
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by pafonta** [comment]
Fixed in [v0.4.0](https://github.com/BlueBrain/neurocurator/tree/v0.4.0).
