### ISSUE TITLE
ValueError: ufunc <ufunc 'positive'> not supported by quantities

### ISSUE THREAD

**Issue by antonkulaga** [BlueBrain/neurocurator#5]
antonkulaga@YOGA ~/neurocurator $ python3 neurocurator/main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/quantities/quantity.py", line 231, in __array_prepare__
    res._dimensionality = p_dict[uf](*objs)
KeyError: <ufunc 'positive'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neurocurator/main.py", line 8, in <module>
    from neurocurator.mainWin import Window
  File "/usr/local/lib/python3.5/dist-packages/neurocurator/mainWin.py", line 21, in <module>
    from nat.utils import Id2FileName #, fileName2Id
  File "/usr/local/lib/python3.5/dist-packages/nat/__init__.py", line 4, in <module>
    from .annotation import Annotation
  File "/usr/local/lib/python3.5/dist-packages/nat/annotation.py", line 10, in <module>
    from .modelingParameter import ParameterInstance, ParamRef
  File "/usr/local/lib/python3.5/dist-packages/nat/modelingParameter.py", line 6, in <module>
    import quantities as pq
  File "/usr/local/lib/python3.5/dist-packages/quantities/__init__.py", line 285, in <module>
    from .units import *
  File "/usr/local/lib/python3.5/dist-packages/quantities/units/__init__.py", line 9, in <module>
    from . import acceleration
  File "/usr/local/lib/python3.5/dist-packages/quantities/units/acceleration.py", line 7, in <module>
    from .time import s
  File "/usr/local/lib/python3.5/dist-packages/quantities/units/time.py", line 18, in <module>
    aliases=['milliseconds']
  File "/usr/local/lib/python3.5/dist-packages/quantities/unitquantity.py", line 62, in __new__
    ret._conv_ref = definition._reference
  File "/usr/local/lib/python3.5/dist-packages/quantities/quantity.py", line 139, in _reference
    rq = rq * u._reference**d
  File "/usr/local/lib/python3.5/dist-packages/quantities/unitquantity.py", line 230, in __pow__
    return self.view(Quantity).__pow__(other)
  File "/usr/local/lib/python3.5/dist-packages/quantities/quantity.py", line 88, in g
    return f(self, other, *args)
  File "/usr/local/lib/python3.5/dist-packages/quantities/quantity.py", line 321, in __pow__
    return super(Quantity, self).__pow__(other)
  File "/usr/local/lib/python3.5/dist-packages/quantities/quantity.py", line 236, in __array_prepare__
    """ % uf
ValueError: ufunc <ufunc 'positive'> not supported by quantities
                please file a bug report at https://github.com/python-quantities

**Comment by christian-oreilly** [comment]
As hinted by the last line of your post ("ValueError: ufunc <ufunc 'positive'> not supported by quantities
please file a bug report at https://github.com/python-quantities"), this is not an issue with the NeuroCurator but an issue with python-quantities. It might be an incompatibility with python 3.4+ since I got the same issues when trying to run the NeuroCurator with Python 3.5. In, any case, this issue has already been reported in [here](https://github.com/python-quantities/python-quantities/issues/128). As mentioned there, this issue is already corrected on the python-quantities development repository. Thus, I would recommend updating your python-quantities package using the code from the repository. E.g., :

`pip3 install --upgrade  git+https://github.com/python-quantities/python-quantities.git`

This fixed the issue for me. As far as I know, this effectively solves the issue so I'm closing this ticket for now. Let me know if you have further issues and I'll reopend it.
