### ISSUE TITLE
Unable to load a PDF in Zotero even if connected to the VPN

### ISSUE THREAD

**Issue by srjimenez** [BlueBrain/neurocurator#55]
Steps:

1. Chose the paper that I wanted to annotate which has no PDF 
2. After having the dialog window "This paper is not already in the curator database" and pressing "select PDF" I get no PDF 

This is the paper I wanted to annotate
(working from home with the VPN on)
Postnatal development of the basolateral complex of rabbit amygdala: a stereological and histochemical study

Stack trace:

```
[sjimenez:~/neurocurator] $ ./neurocurator_0-4-0_mac_x64
Building ontological tree for  PATO:0000261 ... 
Building ontological tree for  NIFORG:birnlex_569 ... 
Building ontological tree for  CHEBI:23367 ... 
Building ontological tree for  GO:0097458 ... 
Building ontological tree for  NIFGA:birnlex_1167 ... 
Building ontological tree for  NIFMOL:nifext_2506 ... 
Building ontological tree for  NIFSUB:sao914572699 ... 
Building ontological tree for  nifext_8054 ... 
Building ontological tree for  sao1813327414 ... 
Loading cached Zotero data...
Cached Zotero data loaded.
2018-01-05 09:26:00.970 neurocurator_0-4-0_mac_x64[46624:1637373] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "urllib/request.py", line 1183, in do_open
  File "http/client.py", line 1137, in request
  File "http/client.py", line 1182, in _send_request
  File "http/client.py", line 1133, in endheaders
  File "http/client.py", line 963, in _send_output
  File "http/client.py", line 898, in send
  File "http/client.py", line 1287, in connect
  File "ssl.py", line 362, in wrap_socket
  File "ssl.py", line 580, in __init__
  File "ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/neurocurator/mainWin.py", line 1008, in paperSelectionChanged
  File "site-packages/neurocurator/mainWin.py", line 1113, in importPDF
  File "site-packages/nat/id.py", line 127, in checkID
  File "site-packages/nat/id.py", line 134, in checkPMID
  File "site-packages/nat/id.py", line 17, in getPMIDSoup
  File "site-packages/nat/id.py", line 26, in getSoup
  File "urllib/request.py", line 161, in urlopen
  File "urllib/request.py", line 470, in open
  File "urllib/request.py", line 580, in http_response
  File "urllib/request.py", line 502, in error
  File "urllib/request.py", line 442, in _call_chain
  File "urllib/request.py", line 685, in http_error_302
  File "urllib/request.py", line 464, in open
  File "urllib/request.py", line 482, in _open
  File "urllib/request.py", line 442, in _call_chain
  File "urllib/request.py", line 1226, in https_open
  File "urllib/request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
2018-01-05 09:31:29.447 neurocurator_0-4-0_mac_x64[46624:1637373] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "urllib/request.py", line 1183, in do_open
  File "http/client.py", line 1137, in request
  File "http/client.py", line 1182, in _send_request
  File "http/client.py", line 1133, in endheaders
  File "http/client.py", line 963, in _send_output
  File "http/client.py", line 898, in send
  File "http/client.py", line 1287, in connect
  File "ssl.py", line 362, in wrap_socket
  File "ssl.py", line 580, in __init__
  File "ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/neurocurator/mainWin.py", line 1008, in paperSelectionChanged
  File "site-packages/neurocurator/mainWin.py", line 1113, in importPDF
  File "site-packages/nat/id.py", line 127, in checkID
  File "site-packages/nat/id.py", line 134, in checkPMID
  File "site-packages/nat/id.py", line 17, in getPMIDSoup
  File "site-packages/nat/id.py", line 26, in getSoup
  File "urllib/request.py", line 161, in urlopen
  File "urllib/request.py", line 470, in open
  File "urllib/request.py", line 580, in http_response
  File "urllib/request.py", line 502, in error
  File "urllib/request.py", line 442, in _call_chain
  File "urllib/request.py", line 685, in http_error_302
  File "urllib/request.py", line 464, in open
  File "urllib/request.py", line 482, in _open
  File "urllib/request.py", line 442, in _call_chain
  File "urllib/request.py", line 1226, in https_open
  File "urllib/request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

```

**Comment by pafonta** [comment]
This isn't a bug of NeuroCurator.
The error comes from missing/outdated SSL certificates - used with the VPN - on your computer.

**Comment by srjimenez** [comment]
The first issue is:
2018-01-05 09:54:47.052 neurocurator_0-4-0_mac_x64[47139:1657724] modalSession has been exited prematurely

**Comment by pafonta** [comment]
The issue was affecting references with a PMID and no DOI [1] but not the ones with a DOI [2]. Both cases are similar. The only differences are the API endpoints and the certification entities. Both URLs are HTTP and not HTTPS in the code, so they aren’t supposed to use SSL. The two methods are getPMIDSoup() for [1] and getDOISoup() for [2] which are in nat/id.py.

At the end, the issue was related to the redirection from HTTP to HTTPS in [1] and most probably to a problem with finding the SSL certificates when packaged. With the new releasing process which came with v0.4.1, there is no more packaging, the issue should therefore not be there any more.
