### ISSUE TITLE
[Annotations] Adding Parameters to Annotations with no tags crashes

### ISSUE THREAD

**Issue by christian-oreilly** [BlueBrain/neurocurator#64]
Steps:

1. Create a new annotation, without adding any tag.
2. Create a new parameter (e.g., age).
3. Try to save. It should fail and produce the following stack trace.

Stack trace:

```
Traceback (most recent call last):
  File "/home/oreilly/GIT_repos/neurocurator/neurocurator/modParamWidgets.py", line 317, in saveParameter
    relationship = self.relationWgt.getRelationship()
  File "/home/oreilly/GIT_repos/neurocurator/neurocurator/paramRelationWgt.py", line 128, in getRelationship
    return Relationship(self.relationshipCbo.currentText(), tag1, tag2)
UnboundLocalError: local variable 'tag1' referenced before assignment

```

**Comment by pafonta** [comment]
What was the reference ID?

I wasn't able to reproduce this behaviour with NeuroCurator v0.4.0 (packaged) and the following steps:

1. In tab _References_, double-click on the reference of ID PMID_7965855.
2. In _Annotations details_, click on _New_.
3. Select 'table' in _Annotation type_.
4. Enter '1' in _Table no._, _Row no._ and _Column_no._.
5. Click on _Save_.
6. Click on the annotation in _Listing of existing annotations_.
7. Click on _Parameters_ on the right panel.
8. Click on _New_.
9. Select 'age' for _Parameter_ in _Parameter details_.
10. Enter '3' in _Values_ and 'week' in _Unit_.
11. Click on _Save_ in _Existing parameters_.
12. No stack trace.

**Comment by pafonta** [comment]
The issue appears when _Relationship_ in _Parameter details_ has a value different from 'unspecified' ('point', 'directed', 'undirected').

When creating a new parameter, it is possible that _Relationship_ has already a value different from 'unspecified' because of #35: the value comes from the previous selected parameter.
