### ISSUE TITLE
[Installation] Crash when trying to start Neurocurator with a new corpus

### ISSUE THREAD

**Issue by davidcsterratt** [BlueBrain/neurocurator#77]
I'm trying out Neurocurator, and I'd like to start with an empty corpus. I had thought that to do this I would create an empty repo on github (e.g. github.com/davidcsterratt/corpus-synaptic-pathways.git), put this in the dialog box, and then be able to start.

However, I get the appended crash. Setting the repository back to github.com/christian-oreilly/corpus-thalamus.git in `miniconda3/envs/nc/lib/python3.4/site-packages/neurocurator/settings.ini` allows Neurocurator to start normally.

```
(nc) 16 $ neurocurator 
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', '__unicode__', '__weakref__', '_cause', '_cmd', '_cmdline', '_msg', 'args', 'command', 'status', 'stderr', 'stdout', 'with_traceback'] ['git', 'pull', '-v', 'origin'] 1   None
Traceback (most recent call last):
  File "/disk/scratch/sterratt/miniconda3/envs/nc/bin/neurocurator", line 11, in <module>
    sys.exit(main())
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/neurocurator/__main__.py", line 15, in main
    window = Window()
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/neurocurator/mainWin.py", line 127, in __init__
    getGitMng()
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/neurocurator/mainWin.py", line 112, in getGitMng
    self.gitMng = GitManager(self.settings.config["GIT"], cleanDirty)
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/nat/gitManager.py", line 64, in __init__
    self.pull(cleanDirty)
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/nat/gitManager.py", line 125, in pull
    fetchInfo = self.repo.remotes.origin.pull()[0]
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/git/remote.py", line 808, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/git/remote.py", line 675, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/disk/scratch/sterratt/miniconda3/envs/nc/lib/python3.4/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin
```

**Comment by pafonta** [comment]
The issue is due to the fact that the Git repository doesn't have a branch `master`.

Unfortunately, the code of NeuroCurator handling Git interactions has not been reviewed yet.

Here is a way to have NeuroCurator working by creating this branch manually:

```
git clone https://github.com/davidcsterratt/corpus-synaptic-pathways
cd corpus-synaptic-pathways
touch README.md
git add README.md
git commit -m "Initialize repository"
git push -u origin master
```

**Comment by davidcsterratt** [comment]
Doh! I'd been trying to keep the repository too clean, as I wasn't sure what was needed there. I've now managed to avoid that error. Still, it would be nice to get this fixed.

**Comment by pafonta** [comment]
Thank you for your interest in the project!
There is currently a lot happening on other aspects of the project which delays some issues fixing...
