### ISSUE TITLE
[Annotations] 

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/neurocurator#96]
NeuroCurator v0.4.4

NeuroCurator crash when trying to specify the 'Synapse' tag.

Steps:
1. Double-click on a reference with annotations.
2. Click on the 'Parameters' tab in the opened 'Annotations' tab.
3. Click on 'New' to create a parameter.
4. Select type 'conductance_synap' for the field 'Parameter' in the panel 'Parameter details'.
5. Double-click on 'Synapse' in the 'Selected tag' column in the panel 'Required tag categories'.

Stack trace:
```
Building ontological tree for  NIFORG:birnlex_569 ... 
Building ontological tree for  PATO:0000261 ... 
Building ontological tree for  CHEBI:23367 ... 
Building ontological tree for  GO:0097458 ... 
Building ontological tree for  NIFGA:birnlex_1167 ... 
Building ontological tree for  NIFMOL:nifext_2506 ... 
Building ontological tree for  NIFSUB:sao914572699 ... 
Building ontological tree for  nifext_8054 ... 
Building ontological tree for  sao1813327414 ... 
Traceback (most recent call last):
  File "/Users/fonta/conda/envs/nc/lib/python3.7/site-packages/neurocurator/modParamWidgets.py", line 40, in setReqTags
    tagId = list(self.dicData.keys())[list(self.dicData.values()).index(tagName)]
ValueError: 'Synapse' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fonta/conda/envs/nc/lib/python3.7/site-packages/neurocurator/modParamWidgets.py", line 45, in setReqTags
    tagId = list(self.dicData.keys())[list(self.dicData.values()).index(tagName)]
ValueError: 'Synapse' is not in list
Abort trap: 6
```

**Comment by pafonta** [comment]
@christian-oreilly We should see together why the tag is not found.

**Comment by christian-oreilly** [comment]
@pafonta Probably the ontology term has been removed from NIF. The software should probably be more robust so that it react in a more graceful way in these cases. In the past, when such a thing happened, I either corrected the term manually (e.g., if an equivalent ontology synonym exist) or added the now missing term to the data/additionsToOntologies.csv file.

In this case, the missing terms seems still to be available (see https://scicrunch.org/scicrunch/interlex/view/ilx_0111398?searchTerm=synapse ), but the preferred curie seemed to have changed from GO:0045202 (used in the thalamus corpus) to SAO:914572699. That might be the source of the issue... the look up of these curie has always been a bit fragile. On long term, it would be nice to find a more robust way to query these terms (e.g., persistent URI... if such persistence can indeed be provided by NIF or another ontology service).

**Comment by pafonta** [comment]
Might be related to https://github.com/BlueBrain/nat/issues/5.
